### ISSUE TITLE
convert.py fails if one rule times out

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa-rules#151]
convert.pyの変換で一つのルールがタイムアウトしたら、全体的に失敗で終わってしまうので、exception handlingで一つのルールがタイムアウトで変換できなくても、そのルールを無視して、変換をし続けるようにしたいです。
（今後もこのような予想外のエラーご起こる可能性があるため）

<img width="1384" alt="Screen Shot 2022-10-14 at 8 34 37" src="https://user-images.githubusercontent.com/71482215/195732768-d2d835f6-28a5-4a3b-a422-b407e1d60a76.png">

`During handling of the above exception, another exception occurred`と書いてありますが、問題の`driver_load_vuln_drivers.yml`を消したら、`convert.py`で無事に変換できました。（なので、原因はtimeoutエラーのようです）

<img width="465" alt="Screen Shot 2022-10-14 at 8 53 31" src="https://user-images.githubusercontent.com/71482215/195732958-a385f960-340c-4bc9-8573-9cf0e429c50d.png">

**Comment by fukusuket** [comment]
**The cause of this issue**
As shown below, it is already handled to catch the exception when executing each sigmac.
https://github.com/Yamato-Security/hayabusa-rules/blob/v1.7.0/tools/sigmac/convert.py#L169-L192

But when **TimeoutExpired** exception occur, 
https://github.com/Yamato-Security/hayabusa-rules/blob/v1.7.0/tools/sigmac/convert.py#L187
`+ "\n" + "Command: " + data.sigma_command`

the above string concat failed(because `data.sigma_command` is list) and **rethrow TypeError inside catch block**.
(that's why `During handling of the above exception, another exception occurred`)

then convert.py failed.

**Step to Reproduce**
(It is difficult to actually generate a sigmac timeout, so a little hack)
1. git clone https://github.com/SigmaHQ/sigma.git
2. change ./tools/sigmac as follows(for raise TimeoutExpired)
```
#!/usr/bin/env python3
import time

from sigma.sigmac import main
time.sleep(61)
main()
```
3. python3 convert.py

**Expected behavior**
convert.py **not failed** as follows.
```
Converting rules. Please wait.
...
x rules where converted! (failed: x)
```
**Actual behavior**
convert.py **failed with stacktrace**.
```
Converting rules. Please wait.
Traceback (most recent call last):
  File "/Users/fukusuke/Scripts/Python/sigma/convert.py", line 170, in sigma_executer
    outs, errs = proc.communicate(timeout=60)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1152, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 2004, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1196, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['python3', './tools/sigmac', '-t', 'hayabusa', '-c', './tools/config/generic/windows-services.yml', '--defer-abort', './rules/windows/win_audit_cve.yml']' timed out after 60 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fukusuke/Scripts/Python/sigma/convert.py", line 242, in <module>
    main()
  File "/Users/fukusuke/Scripts/Python/sigma/convert.py", line 38, in main
    logconverter.convert_rules()
  File "/Users/fukusuke/Scripts/Python/sigma/convert.py", line 82, in convert_rules
    result = threadpool.map(sigma_executer, convert_rule_list)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/fukusuke/Scripts/Python/sigma/convert.py", line 186, in sigma_executer
    logger.error("Timeout Expired, failed to convert " + data.output_path
TypeError: can only concatenate str (not "list") to str
```

**Additional context**
This issue is only when TimeoutExpired occurs. Same issue doesn't happen with other Exceptions.
