### ISSUE TITLE
2.13.0: `tools/sigmac` unit tests are failing

### ISSUE THREAD

**Issue by sf-kastone** [Yamato-Security/hayabusa-rules#605]
```
======================================================================
FAIL: test_create_category_map (test_logsource_mapping.TestLogSourceMapper.test_create_category_map)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\code\hayabusa-rules-2.13.0\tools\sigmac\test_logsource_mapping.py", line 17, in test_create_category_map
    self.assertEquals(len(s4), 68)
AssertionError: 76 != 68

======================================================================
FAIL: test_create_service_map (test_logsource_mapping.TestLogSourceMapper.test_create_service_map)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\code\hayabusa-rules-2.13.0\tools\sigmac\test_logsource_mapping.py", line 8, in test_create_service_map
    self.assertEquals(len(res.keys()), 38)
AssertionError: 43 != 38

----------------------------------------------------------------------
Ran 16 tests in 0.868s
```

**Comment by fukusuket** [comment]
@sf-kastone 
Thank you for reporting the issue :) I'll fix the test.
